# constants.py

GRAPH_DOMAIN = 'https://graph.facebook.com/'
GRAPH_VERSION = 'v18.0'
ENDPOINT_BASE = GRAPH_DOMAIN + GRAPH_VERSION + '/'

ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN'
CLIENT_ID = 'YOUR_CLIENT_ID'
CLIENT_SECRET = 'YOUR_CLIENT_SECRET'
DEBUG_MODE = 'yes'
PAGE_ID = 'YOUR_PAGE_ID'
